name: Execução dos testes unitários com Jest


on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@4

      - name: Configurar Node.JS
        uses: actions/setup-node@v3
        with: 
          node-version: 18
      
      - name: Instalar Dependências
        run: npm install

      - name: Executar Testes
        run: npm run test